### ISSUE TITLE
Issue with version number on the getting started page

### ISSUE THREAD

**Issue by lukelast** [jwstegemann/fritz2-kitchensink#92]
**Describe the bug**
On the kitchen sink getting started page the version number has a **v** in it resulting in `v0.13` but the maven artifact version is actually `0.13`.

**To Reproduce**
1. Go to https://components.fritz2.dev/#Getting%20Started
2. Look for `dev.fritz2:components:v0.13`

**Comment by lukelast** [comment]
Looks like it gets added here: https://github.com/jwstegemann/fritz2-kitchensink/blob/main/src/jsMain/kotlin/dev.fritz2.kitchensink/base/properties.kt#L7

Probably done initially for the benefit of the version displayed in the header.

**Comment by chausknecht** [comment]
Thx for your report :-)
